### ISSUE TITLE
Hi, Can you point out where the code for Contrastive loss？ Thanks

### ISSUE THREAD

**Issue by hulelewin** [JohnsonSign/PointCMP#1]

**Comment by JohnsonSign** [comment]
local contrastive loss: 
https://github.com/JohnsonSign/PointCMP/blob/fa8487713679932b607c1524d1eddcc8cf6985fe/models/CLR_Model.py#L260

In fact, the contrastive loss is transformed into the derived cross-entropy loss, following classical contrastive learning methods such as MoCo and SimCLR.
